name: C Build with Make and Norminette Check (Pip)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        
      - name: Install Norminette
        run: pip install norminette

      - name: Check Norminette style
        run: norminette *.c *.h
        
      - name: Install libbsd
        if: runner.os == 'Linux'
        run: |
          if [[ -f /etc/debian_version ]]; then
            sudo apt-get install -y libbsd-dev
          elif [[ -f /etc/fedora-release ]]; then
            sudo dnf install -y libbsd-devel
          elif [[ -f /etc/alpine-release ]]; then
            apk add libbsd-dev
          else
            echo "Unsupported Linux distribution"
            exit 1
          fi 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Escolha a versão do Python

      - name: Build with Make
        run: make

