name: Norminette Check

on:
  push:
    branches: [ main, master ]  # Ou outras branches que você queira verificar
  pull_request:
    branches: [ main, master ]

jobs:
  norminette:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Norminette
        run: pipx install norminette
      - name: Run Norminette
        run: norminette
